### ISSUE TITLE
issue (ya)

### ISSUE THREAD

**Issue by reciprocates** [Sokisa/PsID-Checker#2]
im 90% sure this ep is hella glitchy and gets alot of server / internal errors.

**Comment by Sokisa** [comment]
> im 90% sure this ep is hella glitchy and gets alot of server / internal errors.

yeh prolly but for now it workes at least , if u want me to add proxies lmk

**Comment by reciprocates** [comment]
> > im 90% sure this ep is hella glitchy and gets alot of server / internal errors.
> 
> yeh prolly but for now it workes at least , if u want me to add proxies lmk

yes the endpoint is hella buggy, it also has like 4 or 6 different responses to be accounted for.
